#!/bin/bash -i
source ~/.bashrc

printf "Running git-hooks/pre-push... \n\n"

RED=$(tput setaf 1)

APP_ROOT="$(dirname "$(dirname "$(readlink -fm "$0")")")"

cd "$APP_ROOT" || exit;

mvn clean install

RESULT=$?

echo $RESULT;

if [[ $RESULT == 0 ]]; then
  echo "Test execution was successful, proceeding with push"
else
  >&2 echo "${RED}ERROR! Some test failed, please fix them and try to push again"
fi

exit $RESULT;